version: "3"

services:
  node:
    build:
      dockerfile: Dockerfile-dev
      context: .
    ports:
      - "9222:9222"
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules

  mysql:
    image: mysql:8
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - mysql_volume:/var/usr/mysql

volumes:
  mysql_volume: